### ISSUE TITLE
程序出错

### ISSUE THREAD

**Issue by AnnaXiong** [Walleclipse/Deep_Speaker-speaker_recognition_system#18]
运行train.py时，提示 No module named numpy ，import ...   as....或者from .... import.....的都会提示这样的错误

**Comment by MichelleYang2017** [comment]
说明你的环境没有这些模块，建议你用anacaonda作为编译器

**Comment by AnnaXiong** [comment]
我用的是PYcharm 运行的，好的，谢谢您

**Comment by MichelleYang2017** [comment]
嗯呢。pycharm可以看成是IDE，但是他也需要编译器，这时候你可以安装一个anaconda来作为解释器，anaconda就像是一个高配版的python，常用的一些python包anaconda中都有。

**Comment by AnnaXiong** [comment]
真的非常感谢，我刚学，有很多东西还不懂，谢谢您

**Comment by AnnaXiong** [comment]
Using TensorFlow backend.
Traceback (most recent call last):
  File "C:/Users/Desktop/Deep_Speaker-speaker_recognition_system-master/Deep_Speaker-speaker_recognition_system-master/train.py", line 21, in <module>
    import select_batch
  File "C:\Users\Desktop\Deep_Speaker-speaker_recognition_system-master\Deep_Speaker-speaker_recognition_system-master\select_batch.py", line 18, in <module>
    from pre_process import data_catalog
  File "C:\Users\Desktop\Deep_Speaker-speaker_recognition_system-master\Deep_Speaker-speaker_recognition_system-master\pre_process.py", line 6, in <module>
    import python_speech_features
ModuleNotFoundError: No module named 'python_speech_features'，
真的不知道怎么解决了，求帮助

**Comment by Walleclipse** [comment]
你好，类似这样的问题你都需要安装相应的库。你可以查看 [python安装第三方库的教程](https://www.jianshu.com/p/bdeb237af302)
一般有两种方法。
1.在命令后台 输入 pip install python_speech_features 
2.直接在pycharm里安装

**Comment by AnnaXiong** [comment]
我看着这个像自己建的库😂，就没安装
