### ISSUE TITLE
运行出错

### ISSUE THREAD

**Issue by AnnaXiong** [Walleclipse/Deep_Speaker-speaker_recognition_system#27]
Traceback (most recent call last):
  File "C:/Users/xiongmeiyan/Desktop/Deep_Speaker-speaker_recognition_system-master/Deep_Speaker-speaker_recognition_system-master/train.py", line 180, in <module>
    main()
  File "C:/Users/xiongmeiyan/Desktop/Deep_Speaker-speaker_recognition_system-master/Deep_Speaker-speaker_recognition_system-master/train.py", line 155, in main
    map(lambda f: os.path.join(c.BEST_CHECKPOINT_FOLDER, f), os.listdir(c.BEST_CHECKPOINT_FOLDER))),
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'best_checkpoint'

求指教

**Comment by Walleclipse** [comment]
你好，这是由于我没有上传best_checkpoint，所以会找不到路径。
你可以自己训练一个模型，或者把`c.BEST_CHECKPOINT_FOLDER` 改成  `c.CHECKPOINT_FOLDER`
我上传的模型在 `checkpoints/` 文件夹 里面

**Comment by AnnaXiong** [comment]
好的，谢谢你。我这个从18000step跑到了18360step了，在cpu上跑的，花了15个多小时，请问这个全部跑完是到第几个step啊

**Comment by Walleclipse** [comment]
我大概跑了10,000多步。具体跑多少步看自己的数据与准确率要求，我也不确定多少步合适。
