### ISSUE TITLE
运行错误

### ISSUE THREAD

**Issue by LittleMaWen** [Walleclipse/Deep_Speaker-speaker_recognition_system#38]
您好学长，我正在复现您的代码，然后出现了错误，我一直没有解决掉，您能帮我看看吗？
Using TensorFlow backend.
Traceback (most recent call last):
  File "train.py", line 22, in <module>
    import select_batch
  File "/home/dcase/mawen/SW/Deep_Speaker-speaker_recognition_system-master/select_batch.py", line 18, in <module>
    from pre_process import data_catalog
  File "/home/dcase/mawen/SW/Deep_Speaker-speaker_recognition_system-master/pre_process.py", line 18, in <module>
    np.set_printoptions(threshold=np.nan)
  File "/home/dcase/miniconda3/lib/python3.7/site-packages/numpy/core/arrayprint.py", line 246, in set_printoptions
    floatmode, legacy)
  File "/home/dcase/miniconda3/lib/python3.7/site-packages/numpy/core/arrayprint.py", line 93, in _make_options_dict
    raise ValueError("threshold must be numeric and non-NAN, try "
ValueError: threshold must be numeric and non-NAN, try sys.maxsize for untruncated representation
我是下载代码后，在ubuntu16.04上运行的，python版本是3.7.3.我首先运行的是python train.py，然后就出现了这个错误，诚盼您的回复，谢谢学长

**Comment by LittleMaWen** [comment]
啊~我修改过来了，要把pre_process.py文件中的threshold=np.nan改成threshold=10000000~

**Comment by LittleMaWen** [comment]
> 您好学长，我正在复现您的代码，然后出现了错误，我一直没有解决掉，您能帮我看看吗？
> Using TensorFlow backend.
> Traceback (most recent call last):
> File "train.py", line 22, in 
> import select_batch
> File "/home/dcase/mawen/SW/Deep_Speaker-speaker_recognition_system-master/select_batch.py", line 18, in 
> from pre_process import data_catalog
> File "/home/dcase/mawen/SW/Deep_Speaker-speaker_recognition_system-master/pre_process.py", line 18, in 
> np.set_printoptions(threshold=np.nan)
> File "/home/dcase/miniconda3/lib/python3.7/site-packages/numpy/core/arrayprint.py", line 246, in set_printoptions
> floatmode, legacy)
> File "/home/dcase/miniconda3/lib/python3.7/site-packages/numpy/core/arrayprint.py", line 93, in _make_options_dict
> raise ValueError("threshold must be numeric and non-NAN, try "
> ValueError: threshold must be numeric and non-NAN, try sys.maxsize for untruncated representation
> 我是下载代码后，在ubuntu16.04上运行的，python版本是3.7.3.我首先运行的是python train.py，然后就出现了这个错误，诚盼您的回复，谢谢学长
